---
# handlers file for grafana-server
- name: daemon reload
  systemd:
    daemon_reload: yes

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: reload prometheus
  shell: kill -HUP $(pgrep prometheus)