---
# tasks file for base-packages
- name: update
  apt:
    update_cache: yes

- name: Upgrade APT packages
  apt:
    upgrade: safe

- name: install package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages }}"