version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_website
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network


networks:
  wordpress_network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"

volumes:
  db_data:
  wordpress_data: