---
# tasks file for loadbalancer
- name: Install HAProxy
  apt:
    name: haproxy
    state: latest
    update_cache: yes

- name: Ensure HAProxy is started and enabled
  systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

        
