---

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download the Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /tmp/grafana.gpg.key
    mode: '0644'

- name: Convert GPG key to dearmored format and save to /etc/apt/keyrings
  command: |
    gpg --dearmor -o /etc/apt/keyrings/grafana.gpg /tmp/grafana.gpg.key
  args:
    creates: /etc/apt/keyrings/grafana.gpg

- name: Remove the temporary GPG key file
  file:
    path: /tmp/grafana.gpg.key
    state: absent

