---
# tasks file for grafana-server
#- name:
#  include_tasks: "nginxinstall.yml"

#- name:
#  include_tasks: "prometheusinstall.yml"

#- name:
#  include_tasks: "grafanainstall.yml"

#- name:
#  include_tasks: "node-exporter.yml"

- name:
  include_tasks: "sometasks.yml"


- name: Restart NGINX service
  service:
    name: nginx.service
    state: restarted

- name: daemon reload
  systemd:
    daemon_reload: yes

- name: Restart the node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: Restart the prometheus
  systemd:
    name: prometheus
    state: restarted

- name: Restart the Grafana server
  systemd:
    name: grafana-server
    state: restarted
