---
- name: Install Python 3
  apt:
    name: 
      - python3
      - python3-venv
    state: present

- name: Create Python virtual environment
  command: python3 -m venv ~/env/ika

- name: Activate virtual environment
  shell: |
    source ~/env/ika/bin/activate
    pip install Flask
    pip install gunicorn
    pip install python-dotenv
    pip install redis
    deactivate
  args:
    executable: /bin/bash


- name: Install pip for Python 3
  apt:
    name: python3-pip
    state: present

- name: Install pip for Python 3
  pip:
    name: redis
    state: present

- name: Flask
  pip:
    name: Flask
    executable: pip3
    state: present

- name: Gunicorn
  pip:
    name: gunicorn
    executable: pip3
    state: present

- name: Install dotenv
  pip:
    name: python-dotenv
    executable: pip3
    state: present

  

